server.port=8080

# JPA/Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# DevTools Configuration
spring.devtools.restart.enabled=true

# Configuracion comun para todos los profiles por defecto
spring.profiles.active=h2

# Debug level Spring
logging.level.org.springframework.web=DEBUG
logging.level.ar.edu.utn.dds=DEBUG

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Metricas
management.datadog.metrics.export.uri=https://api.datadoghq.com
management.datadog.metrics.export.apiKey=${DD_API_KEY:}
management.datadog.metrics.export.applicationKey=${DD_APP_KEY:}
management.datadog.metrics.export.enabled=${DD_METRICS_ENABLED:false}
management.datadog.metrics.export.step=30s
management.metrics.tags.instance=${HOSTNAME:local}

# Analizadores
etiquetador.api.key=${ETIQUETADOR_API_KEY:}
ocr.api.key=${OCR_API_KEY:}

# ? Datos de CloudAMQP (sin TLS, puerto 5672)
spring.rabbitmq.host=toucan.lmq.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=vfstorkm
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:}
spring.rabbitmq.virtual-host=vfstorkm
spring.rabbitmq.ssl.enabled=true
spring.rabbitmq.dynamic=false
# (opcional pero lindo para laburo de cola)
spring.rabbitmq.listener.simple.prefetch=1
spring.rabbitmq.listener.simple.concurrency=1
#spring.rabbitmq.listener.simple.max-concurrency=1
FUENTE_URL=https://fuente-fyffcuepfrdegqar.brazilsouth-01.azurewebsites.net

EXCHANGE=ppdi.exchange
QUEUE=pdis_queue
